using NUnit.Framework;
using BarelyAlive.Rules.Tests.Helpers;
using BarelyAlive.Rules.Tests.Infrastructure;
using TurnForge.Engine.ValueObjects;

namespace BarelyAlive.Rules.Tests.Examples;

/// <summary>
/// Demonstrates the usage of ScenarioRunner for E2E testing.
/// Shows how fluent API simplifies complex test scenarios.
/// </summary>
[TestFixture]
public class ScenarioRunnerExamples
{
    [Test]
    public void Example_InitGame_UsingScenarioRunner()
    {
        // Arrange
        var targetPos = new Position(new TileId(Guid.Parse("07ea7bbc-4f23-4bf0-a5c7-c527f36c3b53")));
        
        // Act & Assert - Fluent Given/When/Then
        ScenarioRunner.Create()
            .GivenMission(TestHelpers.Mission01Json)
            .GivenSurvivors(TestHelpers.MikeId, TestHelpers.DougId)
            .Then(state =>
            {
                var agents = state.GetAgents();
                Assert.That(agents.Count, Is.EqualTo(2), "Should have 2 survivors");
                
                foreach (var agent in agents)
                {
                    Assert.That(agent.PositionComponent.CurrentPosition, Is.EqualTo(targetPos),
                        $"Agent {agent.DefinitionId} should spawn at player spawn position");
                }
            });
    }

    [Test]
    public void Example_BoardInitialization()
    {
        // Act & Assert - Validate board is properly initialized
        ScenarioRunner.Create()
            .GivenMission(TestHelpers.Mission01Json)
            .Then(state =>
            {
                Assert.That(state.Board, Is.Not.Null, "Board should be initialized");
                Assert.That(state.GetProps().Count, Is.EqualTo(12), "Should have 12 props from mission");
            });
    }

    [Test]
    public void Example_PropsSpawned()
    {
       // Act & Assert - Verify props loaded correctly
        ScenarioRunner.Create()
            .GivenMission(TestHelpers.Mission01Json)
            .Then(state =>
            {
                var props = state.GetProps();
                
                // Verify spawn points exist
                var playerSpawn = props.FirstOrDefault(p => p.DefinitionId == "Spawn.Player");
                var zombieSpawn = props.FirstOrDefault(p => p.DefinitionId == "Spawn.Zombie");
                
                Assert.That(playerSpawn, Is.Not.Null, "Player spawn point should exist");
                Assert.That(zombieSpawn, Is.Not.Null, "Zombie spawn point should exist");
            });
    }

    [Test]
    public void Example_EffectValidation()
    {
        // Act & Assert - Validate effects generated by commands
        ScenarioRunner.Create()
            .GivenMission(TestHelpers.Mission01Json)
            .GivenSurvivors(TestHelpers.MikeId)
            .ThenEffects(effects =>
            {
                Assert.That(effects, Is.Not.Empty, "Spawning survivors should generate effects");
                Assert.That(effects.Count, Is.GreaterThan(0), "At least one effect should be generated");
            });
    }
}
